#!/bin/bash
inputfile=$1
data1=""
data2=""
counter=0
bCounter=0
address=""

while read -rn1 data; do
if [[ $counter -eq 0 ]] 
then data1=$data
    ((counter++))
elif [[ $counter -eq 1 ]]
then data2=$data
    ((counter++))
else counter=0
    address=`echo "obase=16 ; $bCounter" | bc`
    echo "16'h"$address "8'h"$data1$data2
    ((bCounter = bCounter + 1))
fi
done < $inputfile